apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-poc
  region: eu-west-1
  version: "1.28"
iam:
  withOIDC: true
managedNodeGroups:
  - name: worker-pool
    instanceType: t4g.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 30
    volumeEncrypted: false
    amiFamily: Bottlerocket
    labels: 
      role: workers
      type: OnDemand
    tags:
      nodegroup-role: Worker
      Environment: POC
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        ebs: true
        cloudWatch: true
    availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
